### ISSUE TITLE
prep for plugin manager

### ISSUE THREAD

**Issue by psifertex** [cxnder/bn-dyldsharedcache#3]
Looks like only two changes are required to get this added to the BN plugin manager. The first is to add a `requirements.txt` -- while ktool and DyldExtractor are versioned, `capstone` is still a requirement of DyldExtractor so it would be nice to expose that.

Or, better yet, replace the [disassembler](https://github.com/cxnder/bn-dyldsharedcache/blob/master/DyldExtractor/converter/objc_fixer.py#L199-L255) with BN's own disassembly to remove the dependency entirely. That also means there's no need to [hack around](https://github.com/cxnder/bn-dyldsharedcache/blob/master/DyldExtractor/converter/objc_fixer.py#L211-L214) the lack of PAC instructions as BN can disassemble those just fine. 

The other step is to [make a release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release), then we can add the plugin directly to the plugin manager which would be really handy!

**Comment by 0cyn** [comment]
Should be resolved, creating a separate issue for removing reliance on capstone
